---
name: CI dev

permissions:
  contents: read

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches-ignore: [main]
  workflow_dispatch:

env:
  TEX_FILENAME: ${{ vars.TEX_FILENAME }}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Build LaTex artifacts
        uses: ./.github/actions/build
