---
name: CI dev

permissions:
  contents: read

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches-ignore: [main]
  workflow_dispatch:

env:
  TEX_FILENAME: ${{ vars.TEX_FILENAME }}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - name: Build LaTex artifacts
        uses: ./.github/actions/build
