---
name: CI dev

permissions:
  contents: read

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches-ignore: [main]
  workflow_dispatch:

env:
  TEX_FILENAME: ${{ vars.TEX_FILENAME }}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      - name: Build LaTex artifacts
        uses: ./.github/actions/build
